# Generated by Django 5.1.6 on 2025-04-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebProjecte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, to='WebProjecte.profile'),
        ),
    ]
