# Generated by Django 4.2.11 on 2025-05-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebProjecte', '0003_friendrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='cardset',
            name='image_url',
        ),
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.ImageField(default='card_images/default.jpg', upload_to='card_images'),
        ),
        migrations.AddField(
            model_name='cardset',
            name='image',
            field=models.ImageField(default='card_sets/default.jpg', upload_to='card_sets'),
        ),
    ]
