# Generated by Django 4.2.11 on 2025-05-13 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WebProjecte', '0004_remove_card_image_url_remove_cardset_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='card_images/default.jpg', upload_to='user_card_images')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('rarity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebProjecte.rarity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
