# Generated by Django 5.1.6 on 2025-05-24 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebProjecte', '0005_alter_card_image_alter_cardset_image'),
        ('WebProjecte', '0005_usercard'),
    ]

    operations = [
    ]
