# Generated by Django 5.1.6 on 2025-05-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebProjecte', '0006_merge_20250524_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='card_images'),
        ),
        migrations.AlterField(
            model_name='cardset',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='card_sets'),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='image',
            field=models.ImageField(upload_to='user_card_images'),
        ),
    ]
